import type { Metadata } from 'next';
import StyledJsxRegistry from '../registry';
import { DashboardLayout } from '@/components';

import 'normalize.css/normalize.css';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledJsxRegistry>
          <DashboardLayout>{children}</DashboardLayout>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
